# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-14 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='text',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
